server:
  port: 25565
  error:
    include-message: always
  servlet:
    context-path: /api/v1
spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:user_db}
    password: ${SPRING_DATASOURCE_PASSWORD:highload}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db-highload}
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: false
      file: dev-compose.yaml
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/master-changelog.xml
    default-schema: public

token:
  expire: 24
  signing:
    key: ${TOKEN_SIGNING_KEY}
admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin}
test:
  username: ${TEST_USERNAME:test}
  password: ${TEST_PASSWORD:test}
